export const Screens = {
  Login: 'Login',
  Register: 'Register',
  Home: 'Home',
  Claim: 'Claim',
  ClaimRequest: 'ClaimRequest',
  AddNewClaim: 'AddNewClaim',
  Certification: 'E-Card',
  Profile: 'Profile',
  Policies: 'Policies',
  EmergencyHelp: 'EmergencyHelp',
  Terms: 'Terms',
  PrivacyPolicy: 'PrivacyPolicy',
  ChangePassword: 'ChangePassword',
  WebView: 'WebViewScreen',
  UserDetails: 'UserDetails',
  ClaimDetails: 'ClaimDetails',
  DraftClaims: 'DraftClaims',
  Notification: 'Notification',
  TrustedHospitals: 'TrustedHospitals',
  Splash: 'Splash',
  Onboard: 'Onboard',
  BottomTab: 'BottomTab',
} as const;
